/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.aaa.bbb.Contract;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2018-09-30")
public class PlantSource implements org.apache.thrift.TBase<PlantSource, PlantSource._Fields>, java.io.Serializable, Cloneable, Comparable<PlantSource> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("PlantSource");

  private static final org.apache.thrift.protocol.TField PLANT_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("plant_code", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField DISPLAY_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("display_name", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField PLANT_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("plant_name", org.apache.thrift.protocol.TType.STRING, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new PlantSourceStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new PlantSourceTupleSchemeFactory();

  public java.lang.String plant_code; // required
  public java.lang.String display_name; // required
  public java.lang.String plant_name; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PLANT_CODE((short)1, "plant_code"),
    DISPLAY_NAME((short)2, "display_name"),
    PLANT_NAME((short)3, "plant_name");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PLANT_CODE
          return PLANT_CODE;
        case 2: // DISPLAY_NAME
          return DISPLAY_NAME;
        case 3: // PLANT_NAME
          return PLANT_NAME;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PLANT_CODE, new org.apache.thrift.meta_data.FieldMetaData("plant_code", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DISPLAY_NAME, new org.apache.thrift.meta_data.FieldMetaData("display_name", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PLANT_NAME, new org.apache.thrift.meta_data.FieldMetaData("plant_name", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(PlantSource.class, metaDataMap);
  }

  public PlantSource() {
  }

  public PlantSource(
    java.lang.String plant_code,
    java.lang.String display_name,
    java.lang.String plant_name)
  {
    this();
    this.plant_code = plant_code;
    this.display_name = display_name;
    this.plant_name = plant_name;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public PlantSource(PlantSource other) {
    if (other.isSetPlant_code()) {
      this.plant_code = other.plant_code;
    }
    if (other.isSetDisplay_name()) {
      this.display_name = other.display_name;
    }
    if (other.isSetPlant_name()) {
      this.plant_name = other.plant_name;
    }
  }

  public PlantSource deepCopy() {
    return new PlantSource(this);
  }

  @Override
  public void clear() {
    this.plant_code = null;
    this.display_name = null;
    this.plant_name = null;
  }

  public java.lang.String getPlant_code() {
    return this.plant_code;
  }

  public PlantSource setPlant_code(java.lang.String plant_code) {
    this.plant_code = plant_code;
    return this;
  }

  public void unsetPlant_code() {
    this.plant_code = null;
  }

  /** Returns true if field plant_code is set (has been assigned a value) and false otherwise */
  public boolean isSetPlant_code() {
    return this.plant_code != null;
  }

  public void setPlant_codeIsSet(boolean value) {
    if (!value) {
      this.plant_code = null;
    }
  }

  public java.lang.String getDisplay_name() {
    return this.display_name;
  }

  public PlantSource setDisplay_name(java.lang.String display_name) {
    this.display_name = display_name;
    return this;
  }

  public void unsetDisplay_name() {
    this.display_name = null;
  }

  /** Returns true if field display_name is set (has been assigned a value) and false otherwise */
  public boolean isSetDisplay_name() {
    return this.display_name != null;
  }

  public void setDisplay_nameIsSet(boolean value) {
    if (!value) {
      this.display_name = null;
    }
  }

  public java.lang.String getPlant_name() {
    return this.plant_name;
  }

  public PlantSource setPlant_name(java.lang.String plant_name) {
    this.plant_name = plant_name;
    return this;
  }

  public void unsetPlant_name() {
    this.plant_name = null;
  }

  /** Returns true if field plant_name is set (has been assigned a value) and false otherwise */
  public boolean isSetPlant_name() {
    return this.plant_name != null;
  }

  public void setPlant_nameIsSet(boolean value) {
    if (!value) {
      this.plant_name = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case PLANT_CODE:
      if (value == null) {
        unsetPlant_code();
      } else {
        setPlant_code((java.lang.String)value);
      }
      break;

    case DISPLAY_NAME:
      if (value == null) {
        unsetDisplay_name();
      } else {
        setDisplay_name((java.lang.String)value);
      }
      break;

    case PLANT_NAME:
      if (value == null) {
        unsetPlant_name();
      } else {
        setPlant_name((java.lang.String)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case PLANT_CODE:
      return getPlant_code();

    case DISPLAY_NAME:
      return getDisplay_name();

    case PLANT_NAME:
      return getPlant_name();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case PLANT_CODE:
      return isSetPlant_code();
    case DISPLAY_NAME:
      return isSetDisplay_name();
    case PLANT_NAME:
      return isSetPlant_name();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof PlantSource)
      return this.equals((PlantSource)that);
    return false;
  }

  public boolean equals(PlantSource that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_plant_code = true && this.isSetPlant_code();
    boolean that_present_plant_code = true && that.isSetPlant_code();
    if (this_present_plant_code || that_present_plant_code) {
      if (!(this_present_plant_code && that_present_plant_code))
        return false;
      if (!this.plant_code.equals(that.plant_code))
        return false;
    }

    boolean this_present_display_name = true && this.isSetDisplay_name();
    boolean that_present_display_name = true && that.isSetDisplay_name();
    if (this_present_display_name || that_present_display_name) {
      if (!(this_present_display_name && that_present_display_name))
        return false;
      if (!this.display_name.equals(that.display_name))
        return false;
    }

    boolean this_present_plant_name = true && this.isSetPlant_name();
    boolean that_present_plant_name = true && that.isSetPlant_name();
    if (this_present_plant_name || that_present_plant_name) {
      if (!(this_present_plant_name && that_present_plant_name))
        return false;
      if (!this.plant_name.equals(that.plant_name))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetPlant_code()) ? 131071 : 524287);
    if (isSetPlant_code())
      hashCode = hashCode * 8191 + plant_code.hashCode();

    hashCode = hashCode * 8191 + ((isSetDisplay_name()) ? 131071 : 524287);
    if (isSetDisplay_name())
      hashCode = hashCode * 8191 + display_name.hashCode();

    hashCode = hashCode * 8191 + ((isSetPlant_name()) ? 131071 : 524287);
    if (isSetPlant_name())
      hashCode = hashCode * 8191 + plant_name.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(PlantSource other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetPlant_code()).compareTo(other.isSetPlant_code());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPlant_code()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.plant_code, other.plant_code);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetDisplay_name()).compareTo(other.isSetDisplay_name());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDisplay_name()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.display_name, other.display_name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetPlant_name()).compareTo(other.isSetPlant_name());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPlant_name()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.plant_name, other.plant_name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("PlantSource(");
    boolean first = true;

    sb.append("plant_code:");
    if (this.plant_code == null) {
      sb.append("null");
    } else {
      sb.append(this.plant_code);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("display_name:");
    if (this.display_name == null) {
      sb.append("null");
    } else {
      sb.append(this.display_name);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("plant_name:");
    if (this.plant_name == null) {
      sb.append("null");
    } else {
      sb.append(this.plant_name);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (plant_code == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'plant_code' was not present! Struct: " + toString());
    }
    if (display_name == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'display_name' was not present! Struct: " + toString());
    }
    if (plant_name == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'plant_name' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PlantSourceStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public PlantSourceStandardScheme getScheme() {
      return new PlantSourceStandardScheme();
    }
  }

  private static class PlantSourceStandardScheme extends org.apache.thrift.scheme.StandardScheme<PlantSource> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, PlantSource struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PLANT_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.plant_code = iprot.readString();
              struct.setPlant_codeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // DISPLAY_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.display_name = iprot.readString();
              struct.setDisplay_nameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // PLANT_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.plant_name = iprot.readString();
              struct.setPlant_nameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, PlantSource struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.plant_code != null) {
        oprot.writeFieldBegin(PLANT_CODE_FIELD_DESC);
        oprot.writeString(struct.plant_code);
        oprot.writeFieldEnd();
      }
      if (struct.display_name != null) {
        oprot.writeFieldBegin(DISPLAY_NAME_FIELD_DESC);
        oprot.writeString(struct.display_name);
        oprot.writeFieldEnd();
      }
      if (struct.plant_name != null) {
        oprot.writeFieldBegin(PLANT_NAME_FIELD_DESC);
        oprot.writeString(struct.plant_name);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PlantSourceTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public PlantSourceTupleScheme getScheme() {
      return new PlantSourceTupleScheme();
    }
  }

  private static class PlantSourceTupleScheme extends org.apache.thrift.scheme.TupleScheme<PlantSource> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, PlantSource struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeString(struct.plant_code);
      oprot.writeString(struct.display_name);
      oprot.writeString(struct.plant_name);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, PlantSource struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.plant_code = iprot.readString();
      struct.setPlant_codeIsSet(true);
      struct.display_name = iprot.readString();
      struct.setDisplay_nameIsSet(true);
      struct.plant_name = iprot.readString();
      struct.setPlant_nameIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

