/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace WMS.PlantFilter.Contract
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class RelPlantWeb : TBase
  {
    private string _plant_name;

    public string Plant_code { get; set; }

    public string Plant_name
    {
      get
      {
        return _plant_name;
      }
      set
      {
        __isset.plant_name = true;
        this._plant_name = value;
      }
    }

    public int Web { get; set; }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool plant_name;
    }

    public RelPlantWeb() {
    }

    public RelPlantWeb(string plant_code, int web) : this() {
      this.Plant_code = plant_code;
      this.Web = web;
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_plant_code = false;
        bool isset_web = false;
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String) {
                Plant_code = iprot.ReadString();
                isset_plant_code = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.String) {
                Plant_name = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.I32) {
                Web = iprot.ReadI32();
                isset_web = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
        if (!isset_plant_code)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Plant_code not set");
        if (!isset_web)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Web not set");
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("RelPlantWeb");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (Plant_code == null)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Plant_code not set");
        field.Name = "plant_code";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Plant_code);
        oprot.WriteFieldEnd();
        if (Plant_name != null && __isset.plant_name) {
          field.Name = "plant_name";
          field.Type = TType.String;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Plant_name);
          oprot.WriteFieldEnd();
        }
        field.Name = "web";
        field.Type = TType.I32;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Web);
        oprot.WriteFieldEnd();
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("RelPlantWeb(");
      __sb.Append(", Plant_code: ");
      __sb.Append(Plant_code);
      if (Plant_name != null && __isset.plant_name) {
        __sb.Append(", Plant_name: ");
        __sb.Append(Plant_name);
      }
      __sb.Append(", Web: ");
      __sb.Append(Web);
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
